name: Hello World 
on:
  push:
    paths:
      - '.github/workflows/blank.yml'
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A demo build"
  
  
  