name: CI Report Example

on: workflow_dispatch

jobs:
  Running_python_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
      
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      
      - name: Rnt the code
        run: python sum-code.py