name: If demo config

on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Ali print
        if: github.actor == 'Ali'
        run: echo "The main branch has changed by ${{ github.actor }} !"
      - name: develop change
        if: github.actor == 'Alirezamoslemi0'
        run: echo "The main branch has changed by ${{ github.actor }} !"
