name: Practice 2
on: workflow_dispatch

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.version }}
    steps:
      - id: step1
        run: echo "version=v1.0.0" >> $GITHUB_OUTPUT

  print-version:
    needs: generate-version
    runs-on: ubuntu-latest
    steps:
      - name: print tag version
        run: echo "The tag version is ${{ needs.generate-version.outputs.output1 }}"