name: Run python code
on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
      - name: run the code
        run: python3 Hello_world.py
      
